(function(g){var window=this;var Xza=function(a,b){return g.Lb(a,b)},$5=function(a,b,c){a.A.set(b,c)},a6=function(a){$5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.F)()).toString(36));
return a},b6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.ln(a.A,b,c)},Yza=function(a,b){var c=[];
g.qk(b,function(d){try{var e=g.ko.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.jo(e)&&c.push(d)},a);
return c},Zza=function(a,b){var c=Yza(a,b);
(0,g.y)(c,function(d){g.ko.prototype.remove.call(this,d)},a)},$za=function(a){if(a.Zc){if(a.Zc.locationOverrideToken)return{locationOverrideToken:a.Zc.locationOverrideToken};
if(null!=a.Zc.latitudeE7&&null!=a.Zc.longitudeE7)return{latitudeE7:a.Zc.latitudeE7,longitudeE7:a.Zc.longitudeE7}}return null},aAa=function(a,b){g.gb(a,b)||a.push(b)},c6=function(a){var b=0,c;
for(c in a)b++;return b},bAa=function(a,b){var c=b instanceof g.zc?b:g.Fc(b,/^data:image\//i.test(b));
a.src=g.Ac(c)},d6=function(){},cAa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},dAa=function(a){if(a.Vd&&"function"==typeof a.Vd)return a.Vd();
if("string"===typeof a)return a.split("");if(g.Oa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Hb(a)},eAa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Oa(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.ff&&"function"==typeof a.ff)var c=a.ff();else if(a.Vd&&"function"==typeof a.Vd)c=void 0;else if(g.Oa(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Ib(a);d=dAa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},fAa=function(a,b,c,d){var e=new g.Zm(null,void 0);
a&&g.$m(e,a);b&&g.an(e,b);c&&g.bn(e,c);d&&(e.u=d);return e},e6=function(a,b){g.So[a]=!0;
var c=g.Qo();c&&c.publish.apply(c,arguments);g.So[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Wm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",gAa(this,a.capabilities||""),hAa(this,a.experiments||""))},gAa=function(a,b){a.capabilities.clear();
(0,g.De)(b.split(","),g.Ta(Xza,iAa)).forEach(function(c){a.capabilities.add(c)})},hAa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},jAa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},kAa=function(a){return new g6(a)},lAa=function(a){return Array.isArray(a)?(0,g.Lc)(a,kAa):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return Array.isArray(a)?"["+(0,g.Lc)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|
0;
return("x"==a?b:b&3|8).toString(16)})},mAa=function(a){return(0,g.Lc)(a,function(b){return{key:b.id,
name:b.name}})},l6=function(a,b){return g.db(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},m6=function(a,b){return g.db(a,function(c){return h6(c,b)})},nAa=function(){var a=(0,g.at)();
a&&Zza(a,a.o.Wh(!0))},n6=function(){var a=g.dt("yt-remote-connected-devices")||[];
g.xb(a);return a},oAa=function(a){if(g.ib(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.Lc)(a,function(d,e){return 0==e?d:d.substring(c.length)})},pAa=function(a){g.ct("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.dt("yt-remote-device-id");a||(a=k6(),g.ct("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.gb(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.gb(a,b);g.ft()&&g.zb(a,b);a=oAa(a);if(g.ib(a))try{g.Dq.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.Eq("remote_sid",a.join(","),-1)}catch(c){}},qAa=function(){return g.dt("yt-remote-session-browser-channel")},rAa=function(){return g.dt("yt-remote-local-screens")||[]},sAa=function(){g.ct("yt-remote-lounge-token-expiration",!0,86400)},tAa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.Lc)(rAa(),function(d){return d.loungeToken}),c=(0,g.Lc)(a,function(d){return d.loungeToken});
(0,g.Di)(c,function(d){return!g.gb(b,d)})&&sAa();
g.ct("yt-remote-local-screens",a,31536E3)},uAa=function(a,b){g.ct("yt-remote-session-browser-channel",a);
g.ct("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.gb(c,d)||c.push(d);pAa(c);q6()},r6=function(a){a||(g.et("yt-remote-session-screen-id"),g.et("yt-remote-session-video-id"));
q6();a=n6();g.lb(a,p6());pAa(a)},vAa=function(){if(!s6){var a=g.qo();
a&&(s6=new g.eo(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},wAa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},xAa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},t6=function(a){a.length?yAa(a.shift(),function(){t6(a)}):u6()},zAa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},yAa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},u6=function(){var a=xAa();
a&&a(!1,"No cast extension found")},BAa=function(){if(AAa){var a=2,b=xAa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;yAa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},CAa=function(){BAa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);t6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},v6=function(a,b,c){g.B.call(this);
this.F=null!=c?(0,g.x)(a,c):a;this.Md=b;this.C=(0,g.x)(this.QG,this);this.o=!1;this.u=0;this.A=this.Ka=null;this.B=[]},w6=function(a,b,c){g.B.call(this);
this.B=null!=c?a.bind(c):a;this.Md=b;this.A=null;this.o=!1;this.u=0;this.Ka=null},x6=function(a){a.Ka=g.dg(function(){a.Ka=null;
a.o&&!a.u&&(a.o=!1,x6(a))},a.Md);
var b=a.A;a.A=null;a.B.apply(null,b)},y6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return cAa(a)},z6=function(){},A6=function(){},DAa=function(){},FAa=function(a){return(a=EAa(a))?new ActiveXObject(a):new XMLHttpRequest},EAa=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},B6=function(a,b,c,d){this.o=a;
this.A=b;this.I=c;this.G=d||1;this.C=45E3;this.B=new g.z1(this);this.u=new g.cg;this.u.setInterval(250)},HAa=function(a,b,c){a.Ql=1;
a.Zh=a6(b.clone());a.jk=c;a.F=!0;GAa(a,null)},C6=function(a,b,c,d,e){a.Ql=1;
a.Zh=a6(b.clone());a.jk=null;a.F=c;e&&(a.zD=!1);GAa(a,d)},GAa=function(a,b){a.Ll=(0,g.F)();
D6(a);a.Ti=a.Zh.clone();b6(a.Ti,"t",a.G);a.vo=0;a.bd=a.o.zt(a.o.co()?b:null);0<a.hu&&(a.Ar=new w6((0,g.x)(a.yE,a,a.bd),a.hu));a.B.ma(a.bd,"readystatechange",a.yO);var c=a.Cj?g.Sb(a.Cj):{};a.jk?(a.ts="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.bd.send(a.Ti,a.ts,a.jk,c)):(a.ts="GET",a.zD&&!g.se&&(c.Connection="close"),a.bd.send(a.Ti,a.ts,null,c));a.o.Vf(1)},KAa=function(a,b,c){for(var d=!0;!a.jj&&a.vo<c.length;){var e=IAa(a,c);
if(e==E6){4==b&&(a.oi=4,F6(15),d=!1);break}else if(e==JAa){a.oi=4;F6(16);d=!1;break}else G6(a,e)}4==b&&0==c.length&&(a.oi=1,F6(17),d=!1);a.eg=a.eg&&d;d||(H6(a),I6(a))},IAa=function(a,b){var c=a.vo,d=b.indexOf("\n",c);
if(-1==d)return E6;c=Number(b.substring(c,d));if(isNaN(c))return JAa;d+=1;if(d+c>b.length)return E6;var e=b.substr(d,c);a.vo=d+c;return e},MAa=function(a,b){a.Ll=(0,g.F)();
D6(a);var c=b?window.location.hostname:"";a.Ti=a.Zh.clone();$5(a.Ti,"DOMAIN",c);$5(a.Ti,"t",a.G);try{a.kg=new ActiveXObject("htmlfile")}catch(n){H6(a);a.oi=7;F6(22);I6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)e+="\\x3c";else if(">"==h)e+="\\x3e";else{var l=h;if(l in J6)h=J6[l];else if(l in LAa)h=J6[l]=LAa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)h=l;else{if(256>m){if(h="\\x",16>m||256<m)h+="0"}else h="\\u",4096>m&&(h+="0");h+=m.toString(16).toUpperCase()}h=
J6[l]=h}e+=h}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.dd(g.dc("b/12014412"),d+"</body></html>");a.kg.open();a.kg.write(g.Zc(c));a.kg.close();a.kg.parentWindow.m=(0,g.x)(a.NN,a);a.kg.parentWindow.d=(0,g.x)(a.DC,a,!0);a.kg.parentWindow.rpcClose=(0,g.x)(a.DC,a,!1);c=a.kg.createElement("DIV");a.kg.parentWindow.document.body.appendChild(c);d=g.Ec(a.Ti.toString());d=g.ld(g.Ac(d));d=g.dd(g.dc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.ed(c,d);a.o.Vf(1)},D6=function(a){a.Zw=(0,g.F)()+a.C;
NAa(a,a.C)},NAa=function(a,b){if(null!=a.Xl)throw Error("WatchDog timer not null");
a.Xl=K6((0,g.x)(a.VN,a),b)},L6=function(a){a.Xl&&(g.v.clearTimeout(a.Xl),a.Xl=null)},I6=function(a){a.o.Ez()||a.jj||a.o.Tp(a)},H6=function(a){L6(a);
g.Pe(a.Ar);a.Ar=null;a.u.stop();g.Cua(a.B);if(a.bd){var b=a.bd;a.bd=null;b.abort();b.dispose()}a.kg&&(a.kg=null)},G6=function(a,b){try{a.o.uC(a,b),a.o.Vf(4)}catch(c){}},PAa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;OAa(a,b,function(h){h?c(!0):g.v.setTimeout(function(){PAa(a,b,c,d,f)},f)})}},OAa=function(a,b,c){var d=new Image;
d.onload=function(){try{M6(d),c(!0)}catch(e){}};
d.onerror=function(){try{M6(d),c(!1)}catch(e){}};
d.onabort=function(){try{M6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{M6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
bAa(d,a)},M6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},QAa=function(a){this.o=a;
this.u=new z6},RAa=function(a){var b=N6(a.o,a.km,"/mail/images/cleardot.gif");
a6(b);PAa(b.toString(),5E3,(0,g.x)(a.NF,a),3,2E3);a.Vf(1)},P6=function(a){var b=a.o.M;
if(null!=b)F6(5),b?(F6(11),O6(a.o,a,!1)):(F6(12),O6(a.o,a,!0));else if(a.Ae=new B6(a,void 0,void 0,void 0),a.Ae.Cj=a.fu,b=a.o,b=N6(b,b.co()?a.Pm:null,a.gu),F6(5),!g.qe||g.Vd(10))b6(b,"TYPE","xmlhttp"),C6(a.Ae,b,!1,a.Pm,!1);else{b6(b,"TYPE","html");var c=a.Ae;a=!!a.Pm;c.Ql=3;c.Zh=a6(b.clone());MAa(c,a)}},Q6=function(a){g.sf.call(this);
this.headers=new g.Wm;this.T=a||null;this.A=!1;this.U=this.o=null;this.ga=this.M="";this.F=0;this.B="";this.C=this.aa=this.I=this.Y=!1;this.G=0;this.N=null;this.fa="";this.R=this.Z=!1},SAa=function(a){return g.qe&&g.Ud(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},TAa=function(a){return"content-type"==a.toLowerCase()},VAa=function(a,b){a.A=!1;
a.o&&(a.C=!0,a.o.abort(),a.C=!1);a.B=b;a.F=5;UAa(a);R6(a)},UAa=function(a){a.Y||(a.Y=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},XAa=function(a){if(a.A&&"undefined"!=typeof g.E1)if(a.U[1]&&4==S6(a)&&2==a.getStatus())T6(a,"Local request error detected and ignored");
else if(a.I&&4==S6(a))g.dg(a.qC,0,a);else if(a.dispatchEvent("readystatechange"),4==S6(a)){T6(a,"Request complete");a.A=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.vd(1,String(a.M));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!WAa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.F=6;try{var l=2<S6(a)?a.o.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";UAa(a)}}finally{R6(a)}}},R6=function(a,b){if(a.o){YAa(a);
var c=a.o,d=a.U[0]?g.La:null;a.o=null;a.U=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},YAa=function(a){a.o&&a.R&&(a.o.ontimeout=null);
a.N&&(g.v.clearTimeout(a.N),a.N=null)},S6=function(a){return a.o?a.o.readyState:0},U6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},T6=function(a,b){return b+" ["+a.ga+" "+a.M+" "+a.getStatus()+"]"},V6=function(a,b,c){this.o=1;
this.u=[];this.B=[];this.C=new z6;this.I=a||null;this.M=null!=b?b:null;this.F=c||!1},ZAa=function(a,b){this.o=a;
this.map=b;this.context=null},$Aa=function(a){g.Re.call(this,"statevent",a)},aBa=function(a,b){g.Re.call(this,"timingevent",a);
this.size=b},bBa=function(a){g.Re.call(this,"serverreachability",a)},eBa=function(a){cBa(a);
if(3==a.o){var b=a.yn++,c=a.Cp.clone();$5(c,"SID",a.A);$5(c,"RID",b);$5(c,"TYPE","terminate");W6(a,c);b=new B6(a,a.A,b,void 0);b.Ql=2;b.Zh=a6(c.clone());bAa(new Image,b.Zh.toString());b.Ll=(0,g.F)();D6(b)}dBa(a)},fBa=function(a){a.oG(1,0);
a.Cp=N6(a,null,a.eu);X6(a)},cBa=function(a){a.ci&&(a.ci.abort(),a.ci=null);
a.Ec&&(a.Ec.cancel(),a.Ec=null);a.Zg&&(g.v.clearTimeout(a.Zg),a.Zg=null);Y6(a);a.me&&(a.me.cancel(),a.me=null);a.hi&&(g.v.clearTimeout(a.hi),a.hi=null)},gBa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new ZAa(a.zK++,b));2!=a.o&&3!=a.o||X6(a)},X6=function(a){a.me||a.hi||(a.hi=K6((0,g.x)(a.CC,a),0),a.Qk=0)},iBa=function(a,b){if(1==a.o){if(!b){a.yn=Math.floor(1E5*Math.random());
var c=a.yn++,d=new B6(a,"",c,void 0);d.Cj=null;var e=Z6(a),f=a.Cp.clone();$5(f,"RID",c);$5(f,"CVER","1");W6(a,f);HAa(d,f,e);a.me=d;a.o=2}}else 3==a.o&&(b?hBa(a,b):0==a.u.length||a.me||hBa(a))},hBa=function(a,b){if(b)if(6<a.kj){a.u=a.B.concat(a.u);
a.B.length=0;var c=a.yn-1;var d=Z6(a)}else c=b.I,d=b.jk;else c=a.yn++,d=Z6(a);var e=a.Cp.clone();$5(e,"SID",a.A);$5(e,"RID",c);$5(e,"AID",a.nl);W6(a,e);c=new B6(a,a.A,c,a.Qk+1);c.Cj=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.me=c;HAa(c,e,d)},W6=function(a,b){if(a.Jd){var c=a.Jd.cz();
c&&g.Bb(c,function(d,e){$5(b,e,d)})}},Z6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.kj&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,h=a.u[e].map;f=6>=a.kj?e:f-d;try{g.Bb(h,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.B=a.B.concat(a.u.splice(0,b));
return c.join("&")},jBa=function(a){a.Ec||a.Zg||(a.G=1,a.Zg=K6((0,g.x)(a.BC,a),0),a.Ck=0)},$6=function(a){if(a.Ec||a.Zg||3<=a.Ck)return!1;
a.G++;a.Zg=K6((0,g.x)(a.BC,a),kBa(a,a.Ck));a.Ck++;return!0},O6=function(a,b,c){a.qs=c;
a.ug=b.qh;a.F||fBa(a)},Y6=function(a){null!=a.oj&&(g.v.clearTimeout(a.oj),a.oj=null)},kBa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a7=function(a,b){if(2==b||9==b){var c=null;
a.Jd&&(c=null);var d=(0,g.x)(a.iP,a);c||(c=new g.Zm("//www.google.com/images/cleardot.gif"),a6(c));OAa(c.toString(),1E4,d)}else F6(2);lBa(a,b)},lBa=function(a,b){a.o=0;
a.Jd&&a.Jd.ry(b);dBa(a);cBa(a)},dBa=function(a){a.o=0;
a.ug=-1;if(a.Jd)if(0==a.B.length&&0==a.u.length)a.Jd.it();else{g.pb(a.B);var b=g.pb(a.u);a.B.length=0;a.u.length=0;a.Jd.it(b)}},N6=function(a,b,c){var d=g.gn(c);
if(""!=d.o)b&&g.an(d,b+"."+d.o),g.bn(d,d.B);else{var e=window.location;d=fAa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Em&&g.Bb(a.Em,function(f,h){$5(d,h,f)});
$5(d,"VER",a.kj);W6(a,d);return d},K6=function(a,b){if(!g.Pa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},F6=function(a){b7.dispatchEvent(new $Aa(b7,a))},mBa=function(){},nBa=function(){this.o=[];
this.u=[]},oBa=function(a,b){this.action=a;
this.params=b||{}},c7=function(a,b){g.B.call(this);
this.o=new g.H(this.GN,0,this);g.D(this,this.o);this.Md=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.x)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a},d7=function(a,b,c){this.N=a;
this.F=b;this.A=new g.$n;this.u=new c7(this.MO,this);this.o=null;this.Pb=!1;this.C=null;this.M="";this.I=this.B=0;this.G=[];this.R=c||!1},pBa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.qs,sessionId:a.o.A,arrayId:a.o.nl}},qBa=function(a,b){a.I=b||0;
a.u.stop();a.o&&(3==a.o.o&&iBa(a.o),eBa(a.o));a.I=0},e7=function(a){return!!a.o&&3==a.o.o},rBa=function(a,b){(a.F.loungeIdToken=b)||a.u.stop()},f7=function(a){this.scheme="https";
this.port=this.domain="";this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.vd(4,a))||"";b&&(this.port=":"+b);this.domain=g.wd(a)||"";a=g.Rc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.wc(a,"10.0")&&(this.u=!1))},g7=function(a,b){var c=a.o;
a.u&&(c=a.scheme+"://"+a.domain+a.port+a.o);return g.Gd(c+b,{})},h7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ta(a.B,d,!0),onError:g.Ta(a.A,e),Re:g.Ta(a.C,e)};c&&(a.Eb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.xq(b,a)},vBa=function(){var a=sBa;
tBa();i7.push(a);uBa(i7)},j7=function(a,b){tBa();
var c=i7,d=wBa(a,String(b));g.ib(c)?xBa(d):(uBa(c),(0,g.y)(c,function(e){e(d)}))},tBa=function(){i7||(i7=g.Ka("yt.mdx.remote.debug.handlers_")||[],g.Ia("yt.mdx.remote.debug.handlers_",i7,void 0))},xBa=function(a){var b=(k7+1)%50;
k7=b;l7[b]=a;m7||(m7=49==b)},uBa=function(a){var b=l7;
if(b[0]){var c=k7,d=m7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
l7=Array(50);k7=-1;m7=!1}},wBa=function(a,b){var c=((0,g.F)()-yBa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},n7=function(a){g.N.call(this);
this.F=a;this.screens=[]},zBa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},ABa=function(a,b){var c=a.screens.length!=b.length;
a.screens=(0,g.De)(a.screens,function(f){return!!l6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=zBa(a,b[d])||c;return c},BBa=function(a,b){var c=a.screens.length;
a.screens=(0,g.De)(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},o7=function(a,b,c,d){g.N.call(this);
this.F=a;this.C=b;this.A=c;this.B=d;this.u=0;this.o=null;this.Ka=NaN},q7=function(a){n7.call(this,"LocalScreenService");
this.u=a;this.o=NaN;p7(this);this.info("Initializing with "+j6(this.screens))},CBa=function(a){if(a.screens.length){var b=(0,g.Lc)(a.screens,function(d){return d.id}),c=g7(a.u,"/pairing/get_lounge_token_batch");
h7(a.u,c,{screen_ids:b.join(",")},(0,g.x)(a.aH,a),(0,g.x)(a.ZG,a))}},p7=function(a){var b=lAa(rAa());
b=(0,g.De)(b,function(c){return!c.uuid});
return ABa(a,b)},r7=function(a,b){tAa((0,g.Lc)(a.screens,jAa));
b&&sAa()},t7=function(a,b){g.N.call(this);
this.F=b;var c=g.dt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.gb(c,l)}this.o=d;this.C=a;this.A=this.B=NaN;this.u=null;s7("Initialized with "+g.Sk(this.o))},DBa=function(a,b,c){var d=g7(a.C,"/pairing/get_screen_availability");
h7(a.C,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},u7=function(a,b){a:if(c6(b)!=c6(a.o))var c=!1;
else{c=g.Ib(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(s7("Updated online screens: "+g.Sk(a.o)),a.o=b,a.S("screenChange"));EBa(a)},v7=function(a){isNaN(a.A)||g.Po(a.A);
a.A=g.No((0,g.x)(a.Xv,a),0<a.B&&a.B<(0,g.F)()?2E4:1E4)},s7=function(a){j7("OnlineScreenService",a)},FBa=function(a){var b={};
(0,g.y)(a.F(),function(c){c.token?b[c.token]=c.id:this.qc("Requesting availability of screen w/o lounge token.")});
return b},EBa=function(a){a=g.Ib(g.Cb(a.o,function(b){return b}));
g.xb(a);a.length?g.ct("yt-remote-online-screen-ids",a.join(","),60):g.et("yt-remote-online-screen-ids")},w7=function(a){n7.call(this,"ScreenService");
this.C=a;this.o=this.u=null;this.A=[];this.B={};GBa(this)},IBa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var h=a.Le();if(h=(c?m6(h,c):null)||m6(h,b)){h.uuid=b;var l=x7(a,h);DBa(a.o,l,function(m){e(m?l:null)})}else c?HBa(a,c,(0,g.x)(function(m){var n=x7(this,new g6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));DBa(this.o,n,function(q){e(q?n:null)})},a),f):e(null)},JBa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},HBa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Eb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.xq(g7(a.C,"/pairing/get_lounge_token_batch"),e)},KBa=function(a){a.screens=a.u.Le();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.screens))},GBa=function(a){y7(a);
a.u=new q7(a.C);a.u.subscribe("screenChange",(0,g.x)(a.hH,a));KBa(a);a.A=lAa(g.dt("yt-remote-automatic-screen-cache")||[]);y7(a);a.info("Initializing automatic screens: "+j6(a.A));a.o=new t7(a.C,(0,g.x)(a.Le,a,!0));a.o.subscribe("screenChange",(0,g.x)(function(){this.S("onlineScreenChange")},a))},x7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.ct("yt-remote-automatic-screen-cache",(0,g.Lc)(a.A,jAa)));y7(a);a.B[b.uuid]=b.id;g.ct("yt-remote-device-id-map",a.B,31536E3);return b},y7=function(a){a.B=g.dt("yt-remote-device-id-map")||{}},z7=function(a,b,c){g.N.call(this);
this.U=c;this.M=a;this.o=b;this.I=null},A7=function(a,b){j7(a.U,b)},B7=function(a,b){z7.call(this,a,b,"CastSession");
this.u=null;this.A=0;this.C=(0,g.x)(this.OP,this);this.B=(0,g.x)(this.eO,this);this.A=g.No((0,g.x)(function(){LBa(this,null)},this),12E4)},MBa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Sk(void 0));
var b={type:"getMdxSessionStatus"};a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.La,(0,g.x)(function(){A7(this,"Failed to send message: getMdxSessionStatus.")},a)):A7(a,"Sending yt message without session: "+g.Sk(b))},LBa=function(a,b){g.Po(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.x)(a.mr,a),d=(0,g.x)(a.Qe,a);a.xz(b,c,d,5)}}else a.Qe(Error("Waiting for session status timed out."))},C7=function(a,b,c){z7.call(this,a,b,"DialSession");
this.A=this.G=null;this.N="";this.T=c;this.B=null;this.F=g.La;this.C=NaN;this.R=(0,g.x)(this.RP,this);this.u=g.La},NBa=function(a){a.u=a.M.EE(a.N,a.o.label,a.o.friendlyName,(0,g.x)(function(b){this.u=g.La;
this.mr(b)},a),(0,g.x)(function(b){this.u=g.La;
this.Qe(b)},a))},OBa=function(a){var b={};
b.pairingCode=a.N;b.theme=a.T;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}vAa()&&(b.env_useStageMdx=1);return g.Ed(b)},D7=function(a,b){z7.call(this,a,b,"ManualSession");
this.u=g.No((0,g.x)(this.ol,this,null),150)},E7=function(a,b,c,d){g.N.call(this);
this.u=a;this.G=b||"233637DE";this.F=c||"cl";this.I=d||!1;this.o=null;this.C=!1;this.A=[];this.B=(0,g.x)(this.VM,this)},PBa=function(a,b){return b?g.db(a.A,function(c){return h6(b,c.label)},a):null},F7=function(a){j7("Controller",a)},sBa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},G7=function(a){return a.C||!!a.A.length||!!a.o},H7=function(a,b,c){b!=a.o&&(g.Pe(a.o),(a.o=b)?(c?a.S("yt-remote-cast2-receiver-resumed",b.o):a.S("yt-remote-cast2-receiver-selected",
b.o),b.subscribe("sessionScreen",(0,g.x)(a.zC,a,b)),b.getScreen()?a.S("yt-remote-cast2-session-change",b.getScreen()):c&&a.o.ol(null)):a.S("yt-remote-cast2-session-change",null))},QBa=function(a){var b=a.u.DE(),c=a.o&&a.o.o;
a=(0,g.Lc)(b,function(d){c&&h6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=PBa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},WBa=function(a,b,c,d,e,f,h){RBa()?SBa(b,e,f,h)&&(J7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?TBa(a,c):(window.__onGCastApiAvailable=function(l,m){l?TBa(a,c):(K7("Failed to load cast API: "+m),L7(!1),J7(!1),g.et("yt-remote-cast-available"),g.et("yt-remote-cast-receiver"),UBa(),c(!1))},d?g.Zo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?CAa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?u6():(BAa(),t6(VBa.map(zAa))))):I7("Cannot initialize because not running Chrome")},UBa=function(){I7("dispose");
var a=M7();a&&a.dispose();g.Ia("yt.mdx.remote.cloudview.instance_",null,void 0);XBa(!1);g.Vo(N7);N7.length=0},O7=function(){return!!g.dt("yt-remote-cast-installed")},YBa=function(){var a=g.dt("yt-remote-cast-receiver");
return a?a.friendlyName:null},ZBa=function(){I7("clearCurrentReceiver");
g.et("yt-remote-cast-receiver")},$Ba=function(){return O7()?M7()?M7().getCastSession():(K7("getCastSelector: Cast is not initialized."),null):(K7("getCastSelector: Cast API is not installed!"),null)},Q7=function(){O7()?M7()?P7()?(I7("Requesting cast selector."),M7().requestSession()):(I7("Wait for cast API to be ready to request the session."),N7.push(g.Uo("yt-remote-cast2-api-ready",Q7))):K7("requestCastSelector: Cast is not initialized."):K7("requestCastSelector: Cast API is not installed!")},R7=
function(a,b){P7()?M7().setConnectedScreenStatus(a,b):K7("setConnectedScreenStatus called before ready.")},RBa=function(){var a=0<=g.Rc.search(/ (CrMo|Chrome|CriOS)\//);
return g.Vw||a},aCa=function(a,b){M7().init(a,b)},SBa=function(a,b,c,d){var e=!1;
M7()||(a=new E7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.ct("yt-remote-cast-available",f);e6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){I7("onReceiverSelected: "+f.friendlyName);
g.ct("yt-remote-cast-receiver",f);e6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){I7("onReceiverResumed: "+f.friendlyName);
g.ct("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){I7("onSessionChange: "+i6(f));
f||g.et("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",f)}),g.Ia("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
I7("cloudview.createSingleton_: "+e);return e},M7=function(){return g.Ka("yt.mdx.remote.cloudview.instance_")},TBa=function(a,b){L7(!0);
J7(!1);aCa(a,function(c){c?(XBa(!0),g.Wo("yt-remote-cast2-api-ready")):(K7("Failed to initialize cast API."),L7(!1),g.et("yt-remote-cast-available"),g.et("yt-remote-cast-receiver"),UBa());b(c)})},I7=function(a){j7("cloudview",a)},K7=function(a){j7("cloudview",a)},L7=function(a){I7("setCastInstalled_ "+a);
g.ct("yt-remote-cast-installed",a)},P7=function(){return!!g.Ka("yt.mdx.remote.cloudview.apiReady_")},XBa=function(a){I7("setApiReady_ "+a);
g.Ia("yt.mdx.remote.cloudview.apiReady_",a,void 0)},J7=function(a){g.Ia("yt.mdx.remote.cloudview.initializing_",a,void 0)},S7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.vg=!1;this.M=this.I=this.u=this.C=0;this.B=NaN;this.A=!1;this.reset(a)},T7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.vg=!1;a.hasNext=!1;a.G=0;a.F=(0,g.F)();a.C=0;a.u=0;a.I=0;a.M=0;a.B=NaN;a.A=!1},U7=function(a){return a.sb()?((0,g.F)()-a.F)/1E3:0},V7=function(a,b){a.G=b;
a.F=(0,g.F)()},W7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.F)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},X7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&T7(a)},Y7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Tb(a.o);b.hasPrevious=a.vg;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.u;b.duration=a.I;b.loadedTime=a.M;b.liveIngestionTime=a.B;return b},$7=function(a,b){g.N.call(this);
this.o=0;this.B=a;this.F=[];this.C=new nBa;this.A=this.u=null;this.M=(0,g.x)(this.fL,this);this.G=(0,g.x)(this.Cn,this);this.I=(0,g.x)(this.eL,this);this.N=(0,g.x)(this.nL,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.dx,this),bCa(this))):c=3;0!=c&&(b?this.dx(c):g.No((0,g.x)(function(){this.dx(c)},this),0));
var d=$Ba();d&&Z7(this,d);this.subscribe("yt-remote-cast2-session-change",this.N)},a8=function(a){return new S7(a.B.getPlayerContextData())},bCa=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.B.subscribe(b,g.Ta(this.SM,b),this))},a)},cCa=function(a){(0,g.y)(a.F,function(b){this.B.unsubscribeByKey(b)},a);
a.F.length=0},b8=function(a,b){var c=a.C;
50>c.o.length+c.u.length&&a.C.u.push(b)},d8=function(a,b,c){var d=a8(a);
V7(d,c);-1E3!=d.playerState&&(d.playerState=b);c8(a,d)},e8=function(a,b,c){a.B.sendMessage(b,c)},c8=function(a,b){cCa(a);
a.B.setPlayerContextData(Y7(b));bCa(a)},Z7=function(a,b){a.A&&(a.A.removeUpdateListener(a.M),a.A.removeMediaListener(a.G),a.Cn(null));
a.A=b;a.A&&(j7("CP","Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.M),a.A.addMediaListener(a.G),a.A.media.length&&a.Cn(a.A.media[0]))},dCa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=a8(a);b.contentId!=d.videoId&&j7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;V7(d,a.u.getEstimatedTime());c8(a,d)}else j7("CP","No cast media video. Ignoring state update.")},f8=function(a,b,c){return(0,g.x)(function(d){this.qc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.qc("Retrying "+b+" using MDx browser channel."),e8(this,b,c))},a)},g8=function(a,b,c){g.N.call(this);
this.C=NaN;this.R=!1;this.I=this.G=this.M=this.N=NaN;this.U=[];this.B=this.F=this.A=this.ib=this.o=null;this.Y=a;this.U.push(g.jp(window,"beforeunload",(0,g.x)(this.TG,this)));this.u=[];this.ib=new S7;this.T=b.id;this.o=eCa(this,c);this.o.subscribe("handlerOpened",this.jL,this);this.o.subscribe("handlerClosed",this.gL,this);this.o.subscribe("handlerError",this.hL,this);this.o.subscribe("handlerMessage",this.iL,this);rBa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.ib.videoId;
g.ft()&&g.ct("yt-remote-session-video-id",d)},this)},h8=function(a){j7("conn",a)},eCa=function(a,b){return new d7(g7(a.Y,"/bc"),b)},i8=function(a,b){a.S("proxyStateChange",b)},fCa=function(a){a.C=g.No((0,g.x)(function(){h8("Connecting timeout");
this.Lk(1)},a),2E4)},j8=function(a){g.Po(a.C);
a.C=NaN},k8=function(a){g.Po(a.N);
a.N=NaN},gCa=function(a){l8(a);
a.M=g.No((0,g.x)(function(){m8(this,"getNowPlaying")},a),2E4)},l8=function(a){g.Po(a.M);
a.M=NaN},iCa=function(a,b){b&&(j8(a),k8(a));
b==(e7(a.o)&&isNaN(a.C))?b&&(i8(a,1),m8(a,"getSubtitlesTrack")):b?(a.vz()&&a.ib.reset(),i8(a,1),m8(a,"getNowPlaying"),hCa(a)):a.Lk(1)},jCa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.ib.videoId&&(g.Pb(b.params)?a.ib.o=null:a.ib.o=b.params,a.S("remotePlayerChange"))},kCa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.ib.listId=b.params.listId||a.ib.listId;X7(a.ib,c,d);a.S("remoteQueueChange")},mCa=function(a,b){b.params=b.params||{};
kCa(a,b);lCa(a,b);a.S("autoplayDismissed")},lCa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
V7(a.ib,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.ib.playerState&&(c=-1E3);a.ib.playerState=c;c=Number(b.params.loadedTime);a.ib.M=isNaN(c)?0:c;c=Number(b.params.duration);a.ib.I=isNaN(c)?0:c;c=a.ib;var d=Number(b.params.liveIngestionTime);c.B=d;c.A=isNaN(d)?!1:!0;c=a.ib;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.ib.playerState?gCa(a):l8(a);a.S("remotePlayerChange")},nCa=function(a,b){if(-1E3!=
a.ib.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.ib.playerState=c;c=parseInt(b.params.currentTime,10);V7(a.ib,isNaN(c)?0:c);a.S("remotePlayerChange")}},oCa=function(a,b){var c="true"==b.params.muted;
a.ib.volume=parseInt(b.params.volume,10);a.ib.muted=c;a.S("remotePlayerChange")},pCa=function(a,b){a.F=b.params.videoId;
a.S("nowAutoplaying",parseInt(b.params.timeout,10))},qCa=function(a,b){var c="true"==b.params.hasNext;
a.ib.vg="true"==b.params.hasPrevious;a.ib.hasNext=c;a.S("previousNextChange")},hCa=function(a){g.Po(a.I);
a.I=g.No((0,g.x)(a.Lk,a,1),864E5)},m8=function(a,b,c){c?h8("Sending: action="+b+", params="+g.Sk(c)):h8("Sending: action="+b);
a.o.sendMessage(b,c)},n8=function(a){n7.call(this,"ScreenServiceProxy");
this.Ld=a;this.o=[];this.o.push(this.Ld.$_s("screenChange",(0,g.x)(this.MP,this)));this.o.push(this.Ld.$_s("onlineScreenChange",(0,g.x)(this.vM,this)))},vCa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.K("MDX_CONFIG")||b;nAa();q6();o8||(o8=new f7(b?b.loungeApiHost:void 0),vAa()&&(o8.o="/api/loungedev"));p8||(p8=g.Ka("yt.mdx.remote.deferredProxies_")||[],g.Ia("yt.mdx.remote.deferredProxies_",p8,void 0));rCa();var c=q8();if(!c){var d=new w7(o8);g.Ia("yt.mdx.remote.screenService_",d,void 0);c=q8();var e=!1,f=void 0,h=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,h=b.theme,l=!!b.disableDial);WBa(a,d,function(m){m?r8()&&R7(r8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){e6("yt-remote-receiver-availability-change")})},e,f,h,l)}b&&!g.Ka("yt.mdx.remote.initialized_")&&(g.Ia("yt.mdx.remote.initialized_",!0,void 0),s8("Initializing: "+g.Sk(b)),t8.push(g.Uo("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),t8.push(g.Uo("yt-remote-cast2-receiver-selected",function(){u8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),t8.push(g.Uo("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),t8.push(g.Uo("yt-remote-cast2-session-change",sCa)),t8.push(g.Uo("yt-remote-connection-change",function(m){m?R7(r8(),"YouTube TV"):v8()||(R7(null,null),ZBa())})),a=w8(),b.isAuto&&(a.id+="#dial"),g.Do("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(h=b.theme)&&(a.theme=h),s8(" -- with channel params: "+
g.Sk(a)),tCa(a),c.start(),r8()||uCa())},xCa=function(){var a=wCa();
O7()&&g.dt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},wCa=function(){var a=q8().Ld.$_gos();
var b=x8();b&&y8()&&(l6(a,b)||a.push(b));return mAa(a)},z8=function(){var a=yCa();
!a&&O7()&&YBa()&&(a={key:"cast-selector-receiver",name:YBa()});return a},yCa=function(){var a=wCa(),b=x8();
b||(b=v8());return g.db(a,function(c){return b&&h6(b,c.key)?!0:!1})},x8=function(){var a=r8();
if(!a)return null;var b=q8().Le();return m6(b,a)},sCa=function(a){s8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=x8();b&&b.id==a.id?R7(b.id,"YouTube TV"):(b&&A8(),B8(a,1))}else y8()&&A8()},A8=function(){P7()?M7().stopSession():K7("stopSession called before API ready.");
var a=y8();a&&(a.disconnect(1),C8(null))},D8=function(){var a=y8();
return!!a&&3!=a.getProxyState()},s8=function(a){j7("remote",a)},q8=function(){if(!E8){var a=g.Ka("yt.mdx.remote.screenService_");
E8=a?new n8(a):null}return E8},r8=function(){return g.Ka("yt.mdx.remote.currentScreenId_")},zCa=function(a){g.Ia("yt.mdx.remote.currentScreenId_",a,void 0)},ACa=function(){return g.Ka("yt.mdx.remote.connectData_")},u8=function(a){g.Ia("yt.mdx.remote.connectData_",a,void 0)},y8=function(){return g.Ka("yt.mdx.remote.connection_")},C8=function(a){var b=y8();
u8(null);a||zCa("");g.Ia("yt.mdx.remote.connection_",a,void 0);p8&&((0,g.y)(p8,function(c){c(a)}),p8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},v8=function(){var a=g.ft();
if(!a)return null;var b=q8();if(!b)return null;b=b.Le();return m6(b,a)},B8=function(a,b){r8();
x8()&&x8();if(F8)G8=a;else{zCa(a.id);var c=new g8(o8,a,w8());c.connect(b,ACa());c.subscribe("beforeDisconnect",function(d){e6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){y8()&&(y8(),C8(null))});
C8(c)}},uCa=function(){var a=v8();
a?(s8("Resume connection to: "+i6(a)),B8(a,0)):(r6(),ZBa(),s8("Skipping connecting because no session screen found."))},rCa=function(){var a=w8();
if(g.Pb(a)){a=p6();var b=g.dt("yt-remote-session-name")||"",c=g.dt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ia("yt.mdx.remote.channelParams_",a,void 0)}},w8=function(){return g.Ka("yt.mdx.remote.channelParams_")||{}},tCa=function(a){a?(g.ct("yt-remote-session-app",a.app),g.ct("yt-remote-session-name",a.name)):(g.et("yt-remote-session-app"),g.et("yt-remote-session-name"));
g.Ia("yt.mdx.remote.channelParams_",a,void 0)},H8=function(a,b,c){g.B.call(this);
var d=this;this.module=a;this.H=b;this.ab=c;this.events=new g.hs(this);this.M=this.events.L(this.H,"onVolumeChange",this.aC);this.B=!1;this.suggestion=null;this.C=new g.lG(64);this.o=new g.H(this.JD,500,this);this.u=new g.H(this.KD,1E3,this);this.G=new v6(this.sP,0,this);this.A={};this.I=new g.H(this.oE,1E3,this);this.F=new w6(this.seekTo,1E3,this);this.N=g.La;g.D(this,this.events);this.events.L(b,"onCaptionsTrackListChanged",this.WL);this.events.L(b,"captionschanged",this.dL);this.events.L(b,"captionssettingschanged",
this.MD);this.events.L(b,"videoplayerreset",this.qr);this.events.L(b,"mdxautoplaycancel",function(){d.ab.My()});
a=this.ab;a.ha();a.subscribe("proxyStateChange",this.tC,this);a.subscribe("remotePlayerChange",this.Jn,this);a.subscribe("remoteQueueChange",this.qr,this);a.subscribe("previousNextChange",this.pC,this);a.subscribe("nowAutoplaying",this.lC,this);a.subscribe("autoplayDismissed",this.KB,this);g.D(this,this.o);g.D(this,this.u);g.D(this,this.G);g.D(this,this.I);g.D(this,this.F);this.MD();this.qr();this.Jn()},BCa=function(a){a.Yb(0);
a.o.stop();a.Oc(new g.lG(64))},J8=function(a,b){if(I8(a)&&!a.B){var c=null;
b&&(c={style:a.H.getSubtitlesUserSettings()},g.Vb(c,b));a.ab.BE(a.H.getVideoData(1).videoId,c);a.A=a8(a.ab).o}},K8=function(a,b){var c=a.H.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.H.getVideoData(1);a.ab.playVideo(c.videoId,b,d,e,c.playerParams,c.kf,$za(c));a.Oc(new g.lG(1))},CCa=function(a,b){if(b){var c=a.H.getOption("captions","tracklist",{Vz:1});
c&&c.length?(a.H.setOption("captions","track",b),a.B=!1):(a.H.loadModule("captions"),a.B=!0)}else a.H.setOption("captions","track",{})},I8=function(a){return a8(a.ab).videoId===a.H.getVideoData(1).videoId},L8=function(){g.U.call(this,{D:"div",
J:"ytp-mdx-manual-pairing-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-title",V:"Connecting to your TV on web using a code will be going away soon"},{D:"div",J:"ytp-mdx-manual-pairing-popup-buttons",K:[{D:"button",W:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],V:"Learn more"},{D:"button",W:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],V:"OK"}]}]}]});this.o=new g.rO(this,250);this.learnMoreButton=
this.ca("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ca("ytp-mdx-manual-pairing-popup-ok");g.D(this,this.o);this.L(this.learnMoreButton,"click",this.u);this.L(this.okButton,"click",this.A)},M8=function(){g.U.call(this,{D:"div",
J:"ytp-mdx-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-popup-title",V:"You're signed out"},{D:"div",J:"ytp-mdx-popup-description",V:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",J:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],V:"Cancel"},{D:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],
V:"Confirm"}]}]}]});this.o=new g.rO(this,250);this.cancelButton=this.ca("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ca("ytp-mdx-privacy-popup-confirm");g.D(this,this.o);this.L(this.cancelButton,"click",this.u);this.L(this.confirmButton,"click",this.A)},N8=function(a){g.U.call(this,{D:"div",
J:"ytp-remote",K:[{D:"div",J:"ytp-remote-display-status",K:[{D:"div",J:"ytp-remote-display-status-icon",K:[g.vM()]},{D:"div",J:"ytp-remote-display-status-text",V:"{{statustext}}"}]}]});this.api=a;this.o=new g.rO(this,250);g.D(this,this.o);this.L(a,"presentingplayerstatechange",this.u);DCa(this,g.tM(a))},DCa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.WL("Error on $RECEIVER_NAME",c):b.sb()||g.T(b,4)?g.WL("Playing on $RECEIVER_NAME",c):g.WL("Connected to $RECEIVER_NAME",c);a.la("statustext",c);a.o.show()}else a.o.hide()},O8=function(a,b){g.LR.call(this,"Play on",0,a,b);
this.H=a;this.Si={};this.L(a,"onMdxReceiversChange",this.B);this.L(a,"presentingplayerstatechange",this.B);this.B()},P8=function(a){g.XN.call(this,a);
this.Qf={key:k6(),name:"This computer"};this.Ge=null;this.subscriptions=[];this.Kv=this.ab=null;this.Si=[this.Qf];this.fi=this.Qf;this.Ub=new g.lG(64);this.mA=0;this.kd=-1;this.ql=null;this.Kn=this.yq=!1;this.ik=this.Hl=null;if(!g.Ly(this.player.O())){a=this.player;var b=g.jN(a);b&&(b=b.zj())&&(b=new O8(a,b),g.D(this,b));b=new N8(a);g.D(this,b);g.JN(a,b.element,4);this.Hl=new M8;g.D(this,this.Hl);g.JN(a,this.Hl.element,4);g.Q(this.player.O().experiments,"pair_servlet_deprecation_warning_enabled")&&
(this.ql=new L8,g.D(this,this.ql),g.JN(a,this.ql.element,4));this.Kn=!!v8();this.yq=!!g.dt("yt-remote-manual-pairing-warning-shown")}},Q8=function(a){a.ik&&(a.player.removeEventListener("presentingplayerstatechange",a.ik),a.ik=null)},ECa=function(a,b,c){a.Ub=c;
a.player.S("presentingplayerstatechange",new g.uG(c,b))},FCa=function(a,b,c){var d=!1;
1===b?d=!a.Kn:2===b&&(d=!a.yq);d&&g.wG(c,8)&&(a.player.pauseVideo(),Q8(a))},R8=function(a,b){if(b.key!==a.fi.key)if(b.key===a.Qf.key)A8();
else{if(a.ql&&!a.yq&&b!==a.Qf&&"cast-selector-receiver"!==b.key&&g.Uy(a.player.O()))GCa(a);else{var c;(c=!g.Q(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.K("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.K("SESSION_INDEX")&&!g.K("LOGGED_IN")))||a.Kn||!a.Hl);(c?0:g.Uy(a.player.O())||g.Yy(a.player.O()))&&HCa(a)}a.fi=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.Q(a.player.O().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Ba(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.kf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=$za(c))&&(d.locationInfo=c);c=d}s8("Connecting to: "+g.Sk(b));"cast-selector-receiver"==b.key?(u8(c||null),c=
c||null,P7()?M7().setLaunchParams(c):K7("setLaunchParams called before ready.")):!c&&D8()&&r8()==b.key?e6("yt-remote-connection-change",!0):(A8(),u8(c||null),c=q8().Le(),(c=m6(c,b.key))&&B8(c,1))}},HCa=function(a){g.tM(a.player).sb()?a.player.pauseVideo():(a.ik=function(b){FCa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.ik));
a.Hl&&a.Hl.Zb();y8()||(F8=!0)},GCa=function(a){g.tM(a.player).sb()?a.player.pauseVideo():(a.ik=function(b){FCa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.ik));
a.ql&&a.ql.Zb();y8()||(F8=!0)},LAa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},J6={"'":"\\'"},ICa={},iAa={tQ:"atp",lT:"ska",WS:"que",kS:"mus",kT:"sus",sR:"dsp",dT:"seq"},s6,o6="",AAa=wAa("loadCastFramework")||wAa("loadCastApplicationFramework"),VBa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Va(v6,g.B);g.k=v6.prototype;g.k.PG=function(a){this.B=arguments;this.o=!1;this.Ka?this.A=(0,g.F)()+this.Md:this.Ka=g.dg(this.C,this.Md)};
g.k.stop=function(){this.Ka&&(g.v.clearTimeout(this.Ka),this.Ka=null);this.A=null;this.o=!1;this.B=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.F.apply(null,this.B)))};
g.k.X=function(){this.stop();v6.uc.X.call(this)};
g.k.QG=function(){this.A?(this.Ka=g.dg(this.C,this.A-(0,g.F)()),this.A=null):(this.Ka=null,this.u?this.o=!0:(this.o=!1,this.F.apply(null,this.B)))};g.t(w6,g.B);g.k=w6.prototype;g.k.AA=function(a){this.A=arguments;this.Ka||this.u?this.o=!0:x6(this)};
g.k.stop=function(){this.Ka&&(g.v.clearTimeout(this.Ka),this.Ka=null,this.o=!1,this.A=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.o||this.Ka||(this.o=!1,x6(this))};
g.k.X=function(){g.B.prototype.X.call(this);this.stop()};z6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
z6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};A6.prototype.o=null;A6.prototype.getOptions=function(){var a;(a=this.o)||(a={},EAa(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Va(DAa,A6);S8=new DAa;g.k=B6.prototype;g.k.Cj=null;g.k.eg=!1;g.k.Xl=null;g.k.Zw=null;g.k.Ll=null;g.k.Ql=null;g.k.Zh=null;g.k.Ti=null;g.k.jk=null;g.k.bd=null;g.k.vo=0;g.k.kg=null;g.k.ts=null;g.k.oi=null;g.k.Qm=-1;g.k.zD=!0;g.k.jj=!1;g.k.hu=0;g.k.Ar=null;var JAa={},E6={};g.k=B6.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.yO=function(a){a=a.target;var b=this.Ar;b&&3==S6(a)?b.AA():this.yE(a)};
g.k.yE=function(a){try{if(a==this.bd)a:{var b=S6(this.bd),c=this.bd.F,d=this.bd.getStatus();if(g.qe&&!g.Vd(10)||g.se&&!g.Ud("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Hh&&!U6(this.bd))break a;this.jj||4!=b||7==c||(8==c||0>=d?this.o.Vf(3):this.o.Vf(2));L6(this);var e=this.bd.getStatus();this.Qm=e;var f=U6(this.bd);(this.eg=200==e)?(4==b&&H6(this),this.F?(KAa(this,b,f),g.Hh&&this.eg&&3==b&&(this.B.ma(this.u,"tick",this.sO),this.u.start())):G6(this,f),this.eg&&!this.jj&&(4==b?this.o.Tp(this):(this.eg=
!1,D6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.oi=3,F6(13)):(this.oi=0,F6(14)),H6(this),I6(this))}}catch(h){this.bd&&U6(this.bd)}finally{}};
g.k.sO=function(){var a=S6(this.bd),b=U6(this.bd);this.vo<b.length&&(L6(this),KAa(this,a,b),this.eg&&4!=a&&D6(this))};
g.k.NN=function(a){K6((0,g.x)(this.MN,this,a),0)};
g.k.MN=function(a){this.jj||(L6(this),G6(this,a),D6(this))};
g.k.DC=function(a){K6((0,g.x)(this.LN,this,a),0)};
g.k.LN=function(a){this.jj||(H6(this),this.eg=a,this.o.Tp(this),this.o.Vf(4))};
g.k.cancel=function(){this.jj=!0;H6(this)};
g.k.VN=function(){this.Xl=null;var a=(0,g.F)();0<=a-this.Zw?(2!=this.Ql&&this.o.Vf(3),H6(this),this.oi=2,F6(18),I6(this)):NAa(this,this.Zw-a)};
g.k.getLastError=function(){return this.oi};g.k=QAa.prototype;g.k.fu=null;g.k.Ae=null;g.k.Br=!1;g.k.Fz=null;g.k.zp=null;g.k.Iu=null;g.k.gu=null;g.k.hf=null;g.k.qh=-1;g.k.Pm=null;g.k.km=null;g.k.connect=function(a){this.gu=a;a=N6(this.o,null,this.gu);F6(3);this.Fz=(0,g.F)();var b=this.o.I;null!=b?(this.Pm=b[0],(this.km=b[1])?(this.hf=1,RAa(this)):(this.hf=2,P6(this))):(b6(a,"MODE","init"),this.Ae=new B6(this,void 0,void 0,void 0),this.Ae.Cj=this.fu,C6(this.Ae,a,!1,null,!0),this.hf=0)};
g.k.NF=function(a){if(a)this.hf=2,P6(this);else{F6(4);var b=this.o;b.ug=b.ci.qh;a7(b,9)}a&&this.Vf(2)};
g.k.zt=function(a){return this.o.zt(a)};
g.k.abort=function(){this.Ae&&(this.Ae.cancel(),this.Ae=null);this.qh=-1};
g.k.Ez=function(){return!1};
g.k.uC=function(a,b){this.qh=a.Qm;if(0==this.hf)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.ug=this.qh;a7(c,2);return}this.Pm=c[0];this.km=c[1]}else c=this.o,c.ug=this.qh,a7(c,2);else if(2==this.hf)if(this.Br)F6(7),this.Iu=(0,g.F)();else if("11111"==b){if(F6(6),this.Br=!0,this.zp=(0,g.F)(),c=this.zp-this.Fz,!g.qe||g.Vd(10)||500>c)this.qh=200,this.Ae.cancel(),F6(12),O6(this.o,this,!0)}else F6(8),this.zp=this.Iu=(0,g.F)(),this.Br=!1};
g.k.Tp=function(){this.qh=this.Ae.Qm;if(this.Ae.eg)0==this.hf?this.km?(this.hf=1,RAa(this)):(this.hf=2,P6(this)):2==this.hf&&((!g.qe||g.Vd(10)?!this.Br:200>this.Iu-this.zp)?(F6(11),O6(this.o,this,!1)):(F6(12),O6(this.o,this,!0)));else{0==this.hf?F6(9):2==this.hf&&F6(10);var a=this.o;this.Ae.getLastError();a.ug=this.qh;a7(a,2)}};
g.k.co=function(){return this.o.co()};
g.k.isActive=function(){return this.o.isActive()};
g.k.Vf=function(a){this.o.Vf(a)};g.Va(Q6,g.sf);var WAa=/^https?$/i,JCa=["POST","PUT"];g.k=Q6.prototype;
g.k.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.M+"; newUri="+a);b=b?b.toUpperCase():"GET";this.M=a;this.B="";this.F=0;this.ga=b;this.Y=!1;this.A=!0;this.o=this.T?FAa(this.T):FAa(S8);this.U=this.T?this.T.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.qC,this);try{d6(T6(this,"Opening Xhr")),this.aa=!0,this.o.open(b,String(a),!0),this.aa=!1}catch(f){d6(T6(this,"Error opening Xhr: "+f.message));VAa(this,f);return}a=
c||"";var e=this.headers.clone();d&&eAa(d,function(f,h){e.set(h,f)});
d=g.db(e.ff(),TAa);c=g.v.FormData&&a instanceof g.v.FormData;!g.gb(JCa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.o.setRequestHeader(h,f)},this);
this.fa&&(this.o.responseType=this.fa);"withCredentials"in this.o&&this.o.withCredentials!==this.Z&&(this.o.withCredentials=this.Z);try{YAa(this),0<this.G&&(this.R=SAa(this.o),d6(T6(this,"Will abort after "+this.G+"ms if incomplete, xhr2 "+this.R)),this.R?(this.o.timeout=this.G,this.o.ontimeout=(0,g.x)(this.Gz,this)):this.N=g.dg(this.Gz,this.G,this)),d6(T6(this,"Sending request")),this.I=!0,this.o.send(a),this.I=!1}catch(f){d6(T6(this,"Send error: "+f.message)),VAa(this,f)}};
g.k.Gz=function(){"undefined"!=typeof g.E1&&this.o&&(this.B="Timed out after "+this.G+"ms, aborting",this.F=8,T6(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.o&&this.A&&(T6(this,"Aborting"),this.A=!1,this.C=!0,this.o.abort(),this.C=!1,this.F=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),R6(this))};
g.k.X=function(){this.o&&(this.A&&(this.A=!1,this.C=!0,this.o.abort(),this.C=!1),R6(this,!0));Q6.uc.X.call(this)};
g.k.qC=function(){this.ha()||(this.aa||this.I||this.C?XAa(this):this.UM())};
g.k.UM=function(){XAa(this)};
g.k.isActive=function(){return!!this.o};
g.k.getStatus=function(){try{return 2<S6(this)?this.o.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.B?this.B:String(this.B)};g.k=V6.prototype;g.k.Em=null;g.k.me=null;g.k.Ec=null;g.k.eu=null;g.k.Cp=null;g.k.gy=null;g.k.Sp=null;g.k.yn=0;g.k.zK=0;g.k.Jd=null;g.k.hi=null;g.k.Zg=null;g.k.oj=null;g.k.ci=null;g.k.qs=null;g.k.nl=-1;g.k.lA=-1;g.k.ug=-1;g.k.Qk=0;g.k.Ck=0;g.k.kj=8;var b7=new g.sf;g.Va($Aa,g.Re);g.Va(aBa,g.Re);g.Va(bBa,g.Re);g.k=V6.prototype;g.k.connect=function(a,b,c,d,e){F6(0);this.eu=b;this.Em=c||{};d&&void 0!==e&&(this.Em.OSID=d,this.Em.OAID=e);this.F?(K6((0,g.x)(this.zy,this,a),100),fBa(this)):this.zy(a)};
g.k.zy=function(a){this.ci=new QAa(this);this.ci.fu=null;this.ci.u=this.C;this.ci.connect(a)};
g.k.Ez=function(){return 0==this.o};
g.k.CC=function(a){this.hi=null;iBa(this,a)};
g.k.BC=function(){this.Zg=null;this.Ec=new B6(this,this.A,"rpc",this.G);this.Ec.Cj=null;this.Ec.hu=0;var a=this.gy.clone();$5(a,"RID","rpc");$5(a,"SID",this.A);$5(a,"CI",this.qs?"0":"1");$5(a,"AID",this.nl);W6(this,a);if(!g.qe||g.Vd(10))$5(a,"TYPE","xmlhttp"),C6(this.Ec,a,!0,this.Sp,!1);else{$5(a,"TYPE","html");var b=this.Ec,c=!!this.Sp;b.Ql=3;b.Zh=a6(a.clone());MAa(b,c)}};
g.k.uC=function(a,b){if(0!=this.o&&(this.Ec==a||this.me==a))if(this.ug=a.Qm,this.me==a&&3==this.o)if(7<this.kj){try{var c=this.C.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Zg){if(this.Ec)if(this.Ec.Ll+3E3<this.me.Ll)Y6(this),this.Ec.cancel(),this.Ec=null;else break a;$6(this);F6(19)}}else this.lA=c[1],0<this.lA-this.nl&&37500>c[2]&&this.qs&&0==this.Ck&&!this.oj&&(this.oj=K6((0,g.x)(this.ZK,this),6E3));else a7(this,11)}else b!=ICa.RQ.o&&a7(this,11);else if(this.Ec==
a&&Y6(this),!g.lc(b)){c=this.C.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.nl=e[0];e=e[1];2==this.o?"c"==e[0]?(this.A=e[1],this.Sp=e[2],e=e[3],null!=e?this.kj=e:this.kj=6,this.o=3,this.Jd&&this.Jd.ty(),this.gy=N6(this,this.co()?this.Sp:null,this.eu),jBa(this)):"stop"==e[0]&&a7(this,7):3==this.o&&("stop"==e[0]?a7(this,7):"noop"!=e[0]&&this.Jd&&this.Jd.sy(e),this.Ck=0)}}};
g.k.ZK=function(){null!=this.oj&&(this.oj=null,this.Ec.cancel(),this.Ec=null,$6(this),F6(20))};
g.k.Tp=function(a){if(this.Ec==a){Y6(this);this.Ec=null;var b=2}else if(this.me==a)this.me=null,b=1;else return;this.ug=a.Qm;if(0!=this.o)if(a.eg)1==b?(b=(0,g.F)()-a.Ll,b7.dispatchEvent(new aBa(b7,a.jk?a.jk.length:0,b,this.Qk)),X6(this),this.B.length=0):jBa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.ug)){if(d=1==b)this.me||this.hi||1==this.o||2<=this.Qk?d=!1:(this.hi=K6((0,g.x)(this.CC,this,a),kBa(this,this.Qk)),this.Qk++,d=!0);d=!(d||2==b&&$6(this))}if(d)switch(c){case 1:a7(this,
5);break;case 4:a7(this,10);break;case 3:a7(this,6);break;case 7:a7(this,12);break;default:a7(this,2)}}};
g.k.oG=function(a){if(!g.gb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.k.iP=function(a){a?F6(2):(F6(1),lBa(this,8))};
g.k.zt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new Q6;a.Z=!1;return a};
g.k.isActive=function(){return!!this.Jd&&this.Jd.isActive(this)};
g.k.Vf=function(a){b7.dispatchEvent(new bBa(b7,a))};
g.k.co=function(){return!(!g.qe||g.Vd(10))};
g.k=mBa.prototype;g.k.ty=function(){};
g.k.sy=function(){};
g.k.ry=function(){};
g.k.it=function(){};
g.k.cz=function(){return{}};
g.k.isActive=function(){return!0};g.k=nBa.prototype;g.k.isEmpty=function(){return g.ib(this.o)&&g.ib(this.u)};
g.k.clear=function(){this.o=[];this.u=[]};
g.k.contains=function(a){return g.gb(this.o,a)||g.gb(this.u,a)};
g.k.remove=function(a){var b=this.o;var c=(0,g.Hua)(b,a);0<=c?(g.kb(b,c),b=!0):b=!1;return b||g.lb(this.u,a)};
g.k.Vd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Va(c7,g.B);g.k=c7.prototype;g.k.GN=function(){this.Md=Math.min(3E5,2*this.Md);this.A();this.u&&this.start()};
g.k.start=function(){var a=this.Md+15E3*Math.random();this.o.jb(a);this.u=(0,g.F)()+a};
g.k.stop=function(){this.o.stop();this.u=0};
g.k.isActive=function(){return this.o.isActive()};
g.k.reset=function(){this.o.stop();this.Md=5E3};g.Va(d7,mBa);g.k=d7.prototype;g.k.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.k.Ki=function(a){return this.A.Dj(a)};
g.k.S=function(a,b){return this.A.S.apply(this.A,arguments)};
g.k.dispose=function(){this.Pb||(this.Pb=!0,g.Pe(this.A),qBa(this),g.Pe(this.u),this.u=null)};
g.k.ha=function(){return this.Pb};
g.k.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.M="";this.u.stop();this.C=a||null;this.B=b||0;a=this.N+"/test";b=this.N+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.R),e=this.o;e&&(e.Jd=null);d.Jd=this;this.o=d;e?this.o.connect(a,b,this.F,e.A,e.nl):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Vb(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):e7(this)&&gBa(this.o,c)};
g.k.ty=function(){this.u.reset();this.C=null;this.B=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)gBa(this.o,a[b])}this.S("handlerOpened")};
g.k.ry=function(a){var b=2==a&&401==this.o.ug;4==a||b||this.u.start();this.S("handlerError",a)};
g.k.it=function(a){if(!this.u.isActive())this.S("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.k.cz=function(){var a={v:2};this.M&&(a.gsessionid=this.M);0!=this.B&&(a.ui=""+this.B);0!=this.I&&(a.ui=""+this.I);this.C&&g.Vb(a,this.C);return a};
g.k.sy=function(a){"S"==a[0]?this.M=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),eBa(this.o)):this.S("handlerMessage",new oBa(a[0],a[1]))};
g.k.MO=function(){this.u.isActive();var a=this.o,b=0;a.Ec&&b++;a.me&&b++;0==b&&this.connect(this.C,this.B)};f7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
f7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
f7.prototype.C=function(a){a(Error("request timed out"))};var yBa=(0,g.F)(),i7=null,l7=Array(50),k7=-1,m7=!1;g.Va(n7,g.N);n7.prototype.Le=function(){return this.screens};
n7.prototype.contains=function(a){return!!l6(this.screens,a)};
n7.prototype.get=function(a){return a?m6(this.screens,a):null};
n7.prototype.info=function(a){j7(this.F,a)};g.t(o7,g.N);g.k=o7.prototype;g.k.start=function(){!this.o&&isNaN(this.Ka)&&this.CE()};
g.k.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ka)||(g.Po(this.Ka),this.Ka=NaN)};
g.k.X=function(){this.stop();g.N.prototype.X.call(this)};
g.k.CE=function(){this.Ka=NaN;this.o=g.xq(g7(this.F,"/pairing/get_screen"),{method:"POST",Eb:{pairing_code:this.C},timeout:5E3,onSuccess:(0,g.x)(this.KP,this),onError:(0,g.x)(this.JP,this),Re:(0,g.x)(this.LP,this)})};
g.k.KP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.A;c.name=this.B;this.S("pairingComplete",new g6(c))};
g.k.JP=function(a){this.o=null;a.status&&404==a.status?this.u>=KCa.length?this.S("pairingFailed",Error("DIAL polling timed out")):(a=KCa[this.u],this.Ka=g.No((0,g.x)(this.CE,this),a),this.u++):this.S("pairingFailed",Error("Server error "+a.status))};
g.k.LP=function(){this.o=null;this.S("pairingFailed",Error("Server not responding"))};
var KCa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Va(q7,n7);g.k=q7.prototype;g.k.start=function(){p7(this)&&this.S("screenChange");!g.dt("yt-remote-lounge-token-expiration")&&CBa(this);g.Po(this.o);this.o=g.No((0,g.x)(this.start,this),1E4)};
g.k.add=function(a,b){p7(this);zBa(this,a);r7(this,!1);this.S("screenChange");b(a);a.token||CBa(this)};
g.k.remove=function(a,b){var c=p7(this);BBa(this,a)&&(r7(this,!1),c=!0);b(a);c&&this.S("screenChange")};
g.k.ks=function(a,b,c,d){var e=p7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,r7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.S("screenChange")};
g.k.X=function(){g.Po(this.o);q7.uc.X.call(this)};
g.k.aH=function(a){p7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}r7(this,!b);b&&j7(this.F,"Missed "+b+" lounge tokens.")};
g.k.ZG=function(a){j7(this.F,"Requesting lounge tokens failed: "+a)};g.t(t7,g.N);g.k=t7.prototype;g.k.start=function(){var a=parseInt(g.dt("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.F)()-144E5<a?0:a)?v7(this):(this.B=(0,g.F)()+3E5,g.ct("yt-remote-fast-check-period",this.B),this.Xv())};
g.k.isEmpty=function(){return g.Pb(this.o)};
g.k.update=function(){s7("Updating availability on schedule.");var a=this.F(),b=g.Cb(this.o,function(c,d){return c&&!!m6(a,d)},this);
u7(this,b)};
g.k.X=function(){g.Po(this.A);this.A=NaN;this.u&&(this.u.abort(),this.u=null);g.N.prototype.X.call(this)};
g.k.Xv=function(){g.Po(this.A);this.A=NaN;this.u&&this.u.abort();var a=FBa(this);if(c6(a)){var b=g7(this.C,"/pairing/get_screen_availability");this.u=h7(this.C,b,{lounge_token:g.Ib(a).join(",")},(0,g.x)(this.qN,this,a),(0,g.x)(this.pN,this))}else u7(this,{}),v7(this)};
g.k.qN=function(a,b){this.u=null;var c=g.Ib(FBa(this));if(g.yb(c,g.Ib(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;u7(this,d);v7(this)}else this.qc("Changing Screen set during request."),this.Xv()};
g.k.pN=function(a){this.qc("Screen availability failed: "+a);this.u=null;v7(this)};
g.k.qc=function(a){j7("OnlineScreenService",a)};g.Va(w7,n7);g.k=w7.prototype;g.k.start=function(){this.u.start();this.o.start();this.screens.length&&(this.S("screenChange"),this.o.isEmpty()||this.S("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.o.update()};
g.k.ks=function(a,b,c,d){this.u.contains(a)?this.u.ks(a,b,c,d):(a="Updating name of unknown screen: "+a.name,j7(this.F,a),d(Error(a)))};
g.k.Le=function(a){return a?this.screens:g.ob(this.screens,(0,g.De)(this.A,function(b){return!this.contains(b)},this))};
g.k.DE=function(){return(0,g.De)(this.Le(!0),function(a){return!!this.o.o[a.id]},this)};
g.k.EE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new o7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(h){g.Pe(f);d(x7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.Pe(f);e(h)});
f.start();return(0,g.x)(f.stop,f)};
g.k.NP=function(a,b,c,d){g.xq(g7(this.C,"/pairing/get_screen"),{method:"POST",Eb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var h=new g6(f.screen||{});if(!h.name||JBa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);JBa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(x7(this,h))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Re:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.k.X=function(){g.Pe(this.u);g.Pe(this.o);w7.uc.X.call(this)};
g.k.hH=function(){KBa(this);this.S("screenChange");this.o.update()};
w7.prototype.dispose=w7.prototype.dispose;g.Va(z7,g.N);g.k=z7.prototype;g.k.getScreen=function(){return this.I};
g.k.mr=function(a){this.I=a;this.S("sessionScreen",this.I)};
g.k.Qe=function(a){this.ha()||(a&&A7(this,""+a),this.I=null,this.S("sessionScreen",null))};
g.k.info=function(a){j7(this.U,a)};
g.k.GE=function(){return null};
g.k.jw=function(a){var b=this.o;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){A7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.X=function(){this.jw("");z7.uc.X.call(this)};g.t(B7,z7);g.k=B7.prototype;g.k.iw=function(a){if(this.u){if(this.u==a)return;A7(this,"Overriding cast sesison with new session object");this.u.removeUpdateListener(this.C);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.u=a;this.u.addUpdateListener(this.C);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);MBa(this)};
g.k.ol=function(a){this.info("launchWithParams no-op for Cast: "+g.Sk(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.x)(function(){this.Qe()},this),(0,g.x)(function(){this.Qe(Error("Failed to stop receiver app."))},this)):this.Qe(Error("Stopping cast device witout session."))};
g.k.jw=function(){};
g.k.X=function(){this.info("disposeInternal");g.Po(this.A);this.A=0;this.u&&(this.u.removeUpdateListener(this.C),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.u=null;z7.prototype.X.call(this)};
g.k.eO=function(a,b){if(!this.ha())if(b){var c=y6(b);if(g.Qa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Sk(c));switch(d){case "mdxSessionStatus":LBa(this,c.screenId);break;default:A7(this,"Unknown youtube message: "+d)}}else A7(this,"Unable to parse message.")}else A7(this,"No data in message.")};
g.k.xz=function(a,b,c,d){IBa(this.M,this.o.label,a,this.o.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(A7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.No((0,g.x)(this.xz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.GE=function(){return this.u};
g.k.OP=function(a){this.ha()||a||(A7(this,"Cast session died."),this.Qe())};g.t(C7,z7);g.k=C7.prototype;g.k.iw=function(a){this.A=a;this.A.addUpdateListener(this.R)};
g.k.ol=function(a){this.B=a;this.F()};
g.k.stop=function(){this.u();this.u=g.La;g.Po(this.C);this.A?this.A.stop((0,g.x)(this.Qe,this,null),(0,g.x)(this.Qe,this,"Failed to stop DIAL device.")):this.Qe()};
g.k.X=function(){this.u();this.u=g.La;g.Po(this.C);this.A&&this.A.removeUpdateListener(this.R);this.A=null;z7.prototype.X.call(this)};
g.k.RP=function(a){this.ha()||a||(A7(this,"DIAL session died."),this.u(),this.u=g.La,this.Qe())};
g.k.ru=function(a){this.N=k6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,OBa(this));a(b);NBa(this)}else this.F=(0,g.x)(function(){g.Po(this.C);this.F=g.La;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,OBa(this));a(c);NBa(this)},this),this.C=g.No((0,g.x)(function(){this.F()},this),100)};
g.k.yH=function(a,b,c){IBa(this.M,this.G.receiver.label,a,this.o.friendlyName,(0,g.x)(function(d){d&&d.token?(this.mr(d),b(new chrome.cast.DialLaunchResponse(!1))):this.ru(b,c)},this),(0,g.x)(function(d){A7(this,"Failed to get DIAL screen: "+d);
this.ru(b,c)},this))};g.t(D7,z7);D7.prototype.stop=function(){this.Qe()};
D7.prototype.iw=function(){};
D7.prototype.ol=function(){g.Po(this.u);this.u=NaN;var a=m6(this.M.Le(),this.o.label);a?this.mr(a):this.Qe(Error("No such screen"))};
D7.prototype.X=function(){g.Po(this.u);this.u=NaN;z7.prototype.X.call(this)};g.t(E7,g.N);g.k=E7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.I||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.ZM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.xC,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.uL,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ha()||
(chrome.cast.addReceiverActionListener(this.B),vBa(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.FE,this)),this.A=QBa(this),chrome.cast.setCustomReceivers(this.A,g.La,(0,g.x)(function(h){this.qc("Failed to set initial custom receivers: "+g.Sk(h))},this)),this.S("yt-remote-cast2-availability-change",G7(this)),b(!0))},this),(0,g.x)(function(h){this.qc("Failed to initialize API: "+g.Sk(h));
b(!1)},this))};
g.k.TO=function(a,b){F7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.getScreen();if(!a||c&&c.id!=a)F7("Unsetting old screen status: "+this.o.o.friendlyName),H7(this,null)}if(a&&b){if(!this.o){c=m6(this.u.Le(),a);if(!c){F7("setConnectedScreenStatus: Unknown screen.");return}var d=PBa(this,c);d||(F7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.A.push(d),chrome.cast.setCustomReceivers(this.A,
g.La,(0,g.x)(function(e){this.qc("Failed to set initial custom receivers: "+g.Sk(e))},this)));
F7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);H7(this,new D7(this.u,d),!0)}this.o.jw(b)}else F7("setConnectedScreenStatus: no screen.")};
g.k.UO=function(a){this.ha()?this.qc("Setting connection data on disposed cast v2"):this.o?this.o.ol(a):this.qc("Setting connection data without a session")};
g.k.QP=function(){this.ha()?this.qc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),H7(this,null)):F7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.xC,this),(0,g.x)(this.tN,this))};
g.k.X=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.FE,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);var a=sBa,b=g.Ka("yt.mdx.remote.debug.handlers_");g.lb(b||[],a);g.Pe(this.o);g.N.prototype.X.call(this)};
g.k.qc=function(a){j7("Controller",a)};
g.k.zC=function(a,b){this.o==a&&(b||H7(this,null),this.S("yt-remote-cast2-session-change",b))};
g.k.VM=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),F7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.o.label!=a.label)F7("onReceiverAction_: Stopping active receiver: "+this.o.o.friendlyName),this.o.stop();else{F7("onReceiverAction_: Casting to active receiver.");this.o.getScreen()&&this.S("yt-remote-cast2-session-change",this.o.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:H7(this,
new D7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:H7(this,new C7(this.u,a,this.F));break;case chrome.cast.ReceiverType.CAST:H7(this,new B7(this.u,a));break;default:this.qc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.o.label==a.label?this.o.stop():this.qc("Stopping receiver w/o session: "+a.friendlyName)}else this.qc("onReceiverAction_ called without receiver.")};
g.k.uL=function(a){if(this.ha())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.qc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.o:null;if(!c||c.label!=b.label)return this.qc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.getScreen())return F7("Reselecting dial screen."),
this.S("yt-remote-cast2-session-change",this.o.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.qc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);H7(this,new C7(this.u,b,this.F))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.yH,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.ru,b))};
g.k.xC=function(a){if(!this.ha()){F7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)F7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),H7(this,new B7(this.u,b),!0);else{this.qc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.o,d=m6(this.u.Le(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(F7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Pe(this.o),this.o=new B7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.zC,this,this.o)),this.o.ol(null));this.o.iw(a)}}};
g.k.PP=function(){return this.o?this.o.GE():null};
g.k.tN=function(a){this.ha()||(this.qc("Failed to estabilish a session: "+g.Sk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&H7(this,null))};
g.k.ZM=function(a){F7("Receiver availability updated: "+a);if(!this.ha()){var b=G7(this);this.C=a==chrome.cast.ReceiverAvailability.AVAILABLE;G7(this)!=b&&this.S("yt-remote-cast2-availability-change",G7(this))}};
g.k.FE=function(){this.ha()||(this.A=QBa(this),F7("Updating custom receivers: "+g.Sk(this.A)),chrome.cast.setCustomReceivers(this.A,g.La,(0,g.x)(function(){this.qc("Failed to set custom receivers.")},this)),this.S("yt-remote-cast2-availability-change",G7(this)))};
E7.prototype.setLaunchParams=E7.prototype.UO;E7.prototype.setConnectedScreenStatus=E7.prototype.TO;E7.prototype.stopSession=E7.prototype.QP;E7.prototype.getCastSession=E7.prototype.PP;E7.prototype.requestSession=E7.prototype.requestSession;E7.prototype.init=E7.prototype.init;E7.prototype.dispose=E7.prototype.dispose;var N7=[];g.k=S7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";T7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.vg=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.u=a.seekableEnd,this.I=a.duration,this.M=a.loadedTime,this.B=a.liveIngestionTime,this.A=!isNaN(this.B))};
g.k.sb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.A?this.I+U7(this):this.I};
g.k.clone=function(){return new S7(Y7(this))};g.t($7,g.N);g.k=$7.prototype;g.k.play=function(){1==this.o?(this.u?this.u.play(null,g.La,f8(this,"play")):e8(this,"play"),d8(this,1,W7(a8(this))),this.S("remotePlayerChange")):b8(this,this.play)};
g.k.pause=function(){1==this.o?(this.u?this.u.pause(null,g.La,f8(this,"pause")):e8(this,"pause"),d8(this,2,W7(a8(this))),this.S("remotePlayerChange")):b8(this,this.pause)};
g.k.seekTo=function(a){if(1==this.o){if(this.u){var b=a8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.sb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.La,f8(this,"seekTo",{newTime:a}))}else e8(this,"seekTo",{newTime:a});d8(this,3,a);this.S("remotePlayerChange")}else b8(this,g.Ta(this.seekTo,a))};
g.k.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.La,f8(this,"stopVideo")):e8(this,"stopVideo");var a=a8(this);a.index=-1;a.videoId="";T7(a);c8(this,a);this.S("remotePlayerChange")}else b8(this,this.stop)};
g.k.setVolume=function(a,b){if(1==this.o){var c=a8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.x)(function(){j7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.qc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.x)(function(){j7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.qc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);e8(this,"setVolume",e)}c.muted=b;c.volume=a;c8(this,c)}else b8(this,g.Ta(this.setVolume,a,b))};
g.k.BE=function(a,b){if(1==this.o){var c=a8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Sk(b.style),g.Vb(d,c.o));e8(this,"setSubtitlesTrack",d);c8(this,c)}else b8(this,g.Ta(this.BE,a,b))};
g.k.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();e8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=a8(this);d.audioTrackId=c;c8(this,d)}else b8(this,g.Ta(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=a8(this);c=c||0;var m={videoId:a,currentIndex:c};X7(l,a,c);void 0!==b&&(V7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Sk(h));e8(this,"setPlaylist",m);d||c8(this,l)};
g.k.wr=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"previous")}else b8(this,g.Ta(this.wr,a,b))};
g.k.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"next")}else b8(this,g.Ta(this.nextVideo,a,b))};
g.k.My=function(){1==this.o?e8(this,"dismissAutoplay"):b8(this,this.My)};
g.k.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.S("proxyStateChange",a,this.o)}g.N.prototype.dispose.call(this)};
g.k.X=function(){cCa(this);this.B=null;this.C.clear();Z7(this,null);g.N.prototype.X.call(this)};
g.k.dx=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.S("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)b=a=this.C,g.ib(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.k.SM=function(a,b){this.S(a,b)};
g.k.fL=function(a){if(!a)this.Cn(null),Z7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=a8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,c8(this,b)}};
g.k.Cn=function(a){j7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.I);if(this.u=a)this.u.addUpdateListener(this.I),dCa(this),this.S("remotePlayerChange")};
g.k.eL=function(a){a?(dCa(this),this.S("remotePlayerChange")):this.Cn(null)};
g.k.Ew=function(){e8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.nL=function(){var a=$Ba();a&&Z7(this,a)};
g.k.qc=function(a){j7("CP",a)};g.t(g8,g.N);g.k=g8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.ib.listId=c);this.ib.videoId=d;this.ib.index=h||0;this.ib.state=3;V7(this.ib,m);this.B="UNSUPPORTED";h8("Connecting with setPlaylist and params: "+g.Sk(l));this.o.connect({method:"setPlaylist",
params:g.Sk(l)},a,qAa())}else h8("Connecting without params"),this.o.connect({},a,qAa());fCa(this)};
g.k.dispose=function(){this.ha()||(this.S("beforeDispose"),i8(this,3));g.N.prototype.dispose.call(this)};
g.k.X=function(){j8(this);l8(this);k8(this);g.Po(this.G);this.G=NaN;g.Po(this.I);this.I=NaN;this.A=null;g.kp(this.U);this.U.length=0;this.o.dispose();g.N.prototype.X.call(this);this.B=this.F=this.u=this.ib=this.o=null};
g.k.TG=function(){this.Lk(2)};
g.k.jL=function(){h8("Channel opened");this.R&&(this.R=!1,k8(this),this.N=g.No((0,g.x)(function(){h8("Timing out waiting for a screen.");this.Lk(1)},this),15E3));
uAa(pBa(this.o),this.T)};
g.k.gL=function(){h8("Channel closed");isNaN(this.C)?r6(!0):r6();this.dispose()};
g.k.hL=function(a){r6();isNaN(this.Lm())?(h8("Channel error: "+a+" without reconnection"),this.dispose()):(this.R=!0,h8("Channel error: "+a+" with reconnection in "+this.Lm()+" ms"),i8(this,2))};
g.k.iL=function(a){a.params?h8("Received: action="+a.action+", params="+g.Sk(a.params)):h8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=y6(a.params.devices);this.u=(0,g.Lc)(a,function(c){return new f6(c)});
a=!!g.db(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
iCa(this,a);break;case "loungeScreenDisconnected":g.nb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
iCa(this,!1);break;case "remoteConnected":var b=new f6(y6(a.params.device));g.db(this.u,function(c){return b?c.id==b.id:!1})||aAa(this.u,b);
break;case "remoteDisconnected":b=new f6(y6(a.params.device));g.nb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":kCa(this,a);break;case "nowPlaying":mCa(this,a);break;case "onStateChange":lCa(this,a);break;case "onAdStateChange":nCa(this,a);break;case "onVolumeChanged":oCa(this,a);break;case "onSubtitlesTrackChanged":jCa(this,a);break;case "nowAutoplaying":pCa(this,a);break;case "autoplayDismissed":this.S("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.S("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.S("autoplayModeChange",this.B);"DISABLED"==this.B&&this.S("autoplayDismissed");break;case "onHasPreviousNextChanged":qCa(this,a);break;case "requestAssistedSignIn":this.S("assistedSignInRequested",a.params.authCode);break;default:h8("Unrecognized action: "+a.action)}};
g.k.IO=function(){if(this.A){var a=this.A;this.A=null;this.ib.videoId!=a&&m8(this,"getNowPlaying")}};
g.k.JG=function(){var a=3;this.ha()||(a=0,isNaN(this.Lm())?e7(this.o)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.Lk=function(a){h8("Disconnecting with "+a);j8(this);this.S("beforeDisconnect",a);1==a&&r6();qBa(this.o,a);this.dispose()};
g.k.HG=function(){var a=this.ib;this.A&&(a=this.ib.clone(),X7(a,this.A,a.index));return Y7(a)};
g.k.VO=function(a){var b=new S7(a);b.videoId&&b.videoId!=this.ib.videoId&&(this.A=b.videoId,g.Po(this.G),this.G=g.No((0,g.x)(this.IO,this),5E3));var c=[];this.ib.listId==b.listId&&this.ib.videoId==b.videoId&&this.ib.index==b.index||c.push("remoteQueueChange");this.ib.playerState==b.playerState&&this.ib.volume==b.volume&&this.ib.muted==b.muted&&W7(this.ib)==W7(b)&&g.Sk(this.ib.o)==g.Sk(b.o)||c.push("remotePlayerChange");this.ib.reset(a);(0,g.y)(c,function(d){this.S(d)},this)};
g.k.vz=function(){var a=this.o.F.id,b=g.db(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Lm=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.F)():NaN};
g.k.wG=function(){return this.B||"UNSUPPORTED"};
g.k.xG=function(){return this.F||""};
g.k.IP=function(){if(!isNaN(this.Lm())){var a=this.o.u;g.En(a.o);a.start()}};
g.k.QO=function(a,b){m8(this,a,b);hCa(this)};
g8.prototype.subscribe=g8.prototype.subscribe;g8.prototype.unsubscribeByKey=g8.prototype.Ki;g8.prototype.getProxyState=g8.prototype.JG;g8.prototype.disconnect=g8.prototype.Lk;g8.prototype.getPlayerContextData=g8.prototype.HG;g8.prototype.setPlayerContextData=g8.prototype.VO;g8.prototype.getOtherConnectedRemoteId=g8.prototype.vz;g8.prototype.getReconnectTimeout=g8.prototype.Lm;g8.prototype.getAutoplayMode=g8.prototype.wG;g8.prototype.getAutoplayVideoId=g8.prototype.xG;g8.prototype.reconnect=g8.prototype.IP;
g8.prototype.sendMessage=g8.prototype.QO;g.t(n8,n7);g.k=n8.prototype;g.k.Le=function(a){return this.Ld.$_gs(a)};
g.k.contains=function(a){return!!this.Ld.$_c(a)};
g.k.get=function(a){return this.Ld.$_g(a)};
g.k.start=function(){this.Ld.$_st()};
g.k.add=function(a,b,c){this.Ld.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Ld.$_r(a,b,c)};
g.k.ks=function(a,b,c,d){this.Ld.$_un(a,b,c,d)};
g.k.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.Ld.$_ubk(this.o[a]);this.o.length=0;this.Ld=null;n7.prototype.X.call(this)};
g.k.MP=function(){this.S("screenChange")};
g.k.vM=function(){this.S("onlineScreenChange")};
w7.prototype.$_st=w7.prototype.start;w7.prototype.$_gspc=w7.prototype.NP;w7.prototype.$_gsppc=w7.prototype.EE;w7.prototype.$_c=w7.prototype.contains;w7.prototype.$_g=w7.prototype.get;w7.prototype.$_a=w7.prototype.add;w7.prototype.$_un=w7.prototype.ks;w7.prototype.$_r=w7.prototype.remove;w7.prototype.$_gs=w7.prototype.Le;w7.prototype.$_gos=w7.prototype.DE;w7.prototype.$_s=w7.prototype.subscribe;w7.prototype.$_ubk=w7.prototype.Ki;var G8=null,F8=!1,o8=null,p8=null,E8=null,t8=[];g.t(H8,g.B);g.k=H8.prototype;g.k.X=function(){g.B.prototype.X.call(this);this.o.stop();this.u.stop();this.G.stop();this.N();var a=this.ab;a.unsubscribe("proxyStateChange",this.tC,this);a.unsubscribe("remotePlayerChange",this.Jn,this);a.unsubscribe("remoteQueueChange",this.qr,this);a.unsubscribe("previousNextChange",this.pC,this);a.unsubscribe("nowAutoplaying",this.lC,this);a.unsubscribe("autoplayDismissed",this.KB,this);this.ab=this.module=null};
g.k.QA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.ab.o)if(I8(this)){if(!a8(this.ab).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":a8(this.ab).sb()?this.ab.pause():this.ab.play();break;case "control_play":this.ab.play();break;case "control_pause":this.ab.pause();break;case "control_seek":this.F.AA(c[0],c[1]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.H.getCurrentTime();K8(this,0===c?void 0:c);break;case "control_seek":K8(this,c[0]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.dL=function(a){this.G.PG(a)};
g.k.sP=function(a){this.QA("control_subtitles_set_track",g.Pb(a)?null:a)};
g.k.MD=function(){var a=this.H.getOption("captions","track");g.Pb(a)||J8(this,a)};
g.k.Yb=function(a){this.module.Yb(a,this.H.getVideoData().lengthSeconds)};
g.k.aC=function(a){if(I8(this)){this.ab.unsubscribe("remotePlayerChange",this.Jn,this);var b=Math.round(a.volume);a=!!a.muted;var c=a8(this.ab);if(b!==c.volume||a!==c.muted)this.ab.setVolume(b,a),this.I.start();this.ab.subscribe("remotePlayerChange",this.Jn,this)}};
g.k.WL=function(){g.Pb(this.A)||CCa(this,this.A);this.B=!1};
g.k.tC=function(a,b){this.u.stop();2===b&&this.KD()};
g.k.Jn=function(){if(I8(this)){this.o.stop();var a=a8(this.ab);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.module.kd=1;break;case 1082:case 1083:this.module.kd=0;break;default:this.module.kd=-1}switch(a.playerState){case 1081:case 1:this.Oc(new g.lG(8));this.JD();break;case 1085:case 3:this.Oc(new g.lG(9));break;case 1083:case 0:this.Oc(new g.lG(2));this.F.stop();this.Yb(this.H.getVideoData().lengthSeconds);break;case 1084:this.Oc(new g.lG(4));break;case 2:this.Oc(new g.lG(4));
this.Yb(W7(a));break;case -1:this.Oc(new g.lG(64));break;case -1E3:this.Oc(new g.lG(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=a8(this.ab).o;var b=this.A;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.A=a,CCa(this,a));a=a8(this.ab);-1===a.volume||Math.round(this.H.getVolume())===a.volume&&this.H.isMuted()===a.muted||this.I.isActive()||this.oE()}else BCa(this)};
g.k.pC=function(){this.H.S("mdxpreviousnextchange")};
g.k.qr=function(){I8(this)||BCa(this)};
g.k.lC=function(a){isNaN(a)||this.H.S("mdxnowautoplaying",a)};
g.k.KB=function(){this.H.S("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){I8(this)&&this.ab.setAudioTrack(this.H.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===a8(this.ab).playerState?K8(this,a):b&&this.ab.seekTo(a)};
g.k.oE=function(){if(I8(this)){var a=a8(this.ab);this.events.ob(this.M);a.muted?this.H.mute():this.H.unMute();this.H.setVolume(a.volume);this.M=this.events.L(this.H,"onVolumeChange",this.aC)}};
g.k.JD=function(){this.o.stop();if(!this.ab.ha()){var a=a8(this.ab);a.sb()&&this.Oc(new g.lG(8));this.Yb(W7(a));this.o.start()}};
g.k.KD=function(){this.u.stop();this.o.stop();var a=this.ab.B.getReconnectTimeout();2==this.ab.o&&!isNaN(a)&&this.u.start()};
g.k.Oc=function(a){this.u.stop();var b=this.C;if(!g.qG(b,a)){var c=g.T(a,2);c!==g.T(this.C,2)&&g.cU(this.H.app,c);this.C=a;ECa(this.module,b,a)}};g.t(L8,g.U);L8.prototype.Zb=function(){this.o.show()};
L8.prototype.Sa=function(){this.o.hide()};
L8.prototype.u=function(){g.yO("https://support.google.com/youtube/answer/7640706")};
L8.prototype.A=function(){e6("mdx-manual-pairing-popup-ok");this.Sa()};g.t(M8,g.U);M8.prototype.Zb=function(){this.o.show()};
M8.prototype.Sa=function(){this.o.hide()};
M8.prototype.u=function(){e6("mdx-privacy-popup-cancel");this.Sa()};
M8.prototype.A=function(){e6("mdx-privacy-popup-confirm");this.Sa()};g.t(N8,g.U);N8.prototype.u=function(a){DCa(this,a.state)};g.t(O8,g.LR);O8.prototype.B=function(){var a=this.H.getOption("remote","receivers");a&&1<a.length&&!this.H.getOption("remote","quickCast")?(this.Si=g.Ab(a,this.o,this),g.NR(this,(0,g.Lc)(a,this.o)),a=this.H.getOption("remote","currentReceiver"),this.Mb(this.o(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.o=function(a){return a.key};
O8.prototype.Tf=function(a){return"cast-selector-receiver"===a?"Cast...":this.Si[a].name};
O8.prototype.xd=function(a){g.LR.prototype.xd.call(this,a);this.H.setOption("remote","currentReceiver",this.Si[a]);this.Ma.Sa()};g.t(P8,g.XN);g.k=P8.prototype;
g.k.create=function(){vCa(g.By(this.player.O()));this.subscriptions.push(g.Uo("yt-remote-before-disconnect",this.bL,this));this.subscriptions.push(g.Uo("yt-remote-connection-change",this.aN,this));this.subscriptions.push(g.Uo("yt-remote-receiver-availability-change",this.rC,this));this.subscriptions.push(g.Uo("yt-remote-auto-connect",this.YM,this));this.subscriptions.push(g.Uo("yt-remote-receiver-resumed",this.XM,this));this.subscriptions.push(g.Uo("mdx-privacy-popup-confirm",this.wO,this));this.subscriptions.push(g.Uo("mdx-privacy-popup-cancel",
this.vO,this));this.subscriptions.push(g.Uo("mdx-manual-pairing-popup-ok",this.TH,this));this.rC()};
g.k.load=function(){this.player.cancelPlayback();g.XN.prototype.load.call(this);this.Ge=new H8(this,this.player,this.ab);var a=(a=ACa())?a.currentTime:0;var b=D8()?new $7(y8(),void 0):null;0==a&&b&&(a=W7(a8(b)));0!==a&&this.Yb(a);ECa(this,this.Ub,this.Ub);g.jU(this.player.app,6)};
g.k.unload=function(){this.player.S("mdxautoplaycanceled");this.fi=this.Qf;g.Qe(this.Ge,this.ab);this.ab=this.Ge=null;g.XN.prototype.unload.call(this);g.jU(this.player.app,5);Q8(this)};
g.k.X=function(){g.Vo(this.subscriptions);g.XN.prototype.X.call(this)};
g.k.Ig=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.Ge.QA.apply(this.Ge,[a].concat(g.ma(c)))};
g.k.getAdState=function(){return this.kd};
g.k.LG=function(){return this.loaded?this.Ge.suggestion:null};
g.k.vg=function(){return this.ab?a8(this.ab).vg:!1};
g.k.hasNext=function(){return this.ab?a8(this.ab).hasNext:!1};
g.k.Yb=function(a,b){this.mA=a||0;this.player.S("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.mA};
g.k.getProgressState=function(){var a=a8(this.ab),b=this.player.getVideoData();return{allowSeeking:g.Q(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.jd():!a.isAdPlaying()&&this.player.jd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.B+U7(a):a.B,isAtLiveHead:1>=(a.A?a.u+U7(a):a.u)-this.getCurrentTime(),loaded:a.M,seekableEnd:a.A?a.u+U7(a):a.u,seekableStart:0<a.C?a.C+
U7(a):a.C}};
g.k.nextVideo=function(){this.ab&&this.ab.nextVideo()};
g.k.wr=function(){this.ab&&this.ab.wr()};
g.k.bL=function(a){1===a&&(this.Kv=this.ab?a8(this.ab):null)};
g.k.aN=function(){var a=D8()?new $7(y8(),void 0):null;if(a){var b=this.fi;this.loaded&&this.unload();this.ab=a;this.Kv=null;b.key!==this.Qf.key&&(this.fi=b,this.load())}else g.Pe(this.ab),this.ab=null,this.loaded&&(this.unload(),(a=this.Kv)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,W7(a)));this.player.S("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.rC=function(){this.Si=[this.Qf].concat(xCa());var a=z8()||this.Qf;R8(this,a);this.player.oa("onMdxReceiversChange")};
g.k.YM=function(){var a=z8();R8(this,a)};
g.k.XM=function(){this.fi=z8()};
g.k.wO=function(){this.Kn=!0;Q8(this);F8=!1;G8&&B8(G8,1);G8=null};
g.k.vO=function(){this.Kn=!1;Q8(this);R8(this,this.Qf);this.fi=this.Qf;F8=!1;G8=null;this.player.playVideo()};
g.k.TH=function(){this.yq=!0;Q8(this);g.ct("yt-remote-manual-pairing-warning-shown",!0,2592E3);F8=!1;G8&&B8(G8,1);G8=null};
g.k.dd=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Si;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?Q7():R8(this,b)),this.loaded?this.fi:this.Qf;case "quickCast":return 2===this.Si.length&&"cast-selector-receiver"===this.Si[1].key?(b&&Q7(),!0):!1}};
g.k.Ew=function(){this.ab.Ew()};
g.k.dg=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.hO.remote=P8;})(_yt_player);
